### ISSUE TITLE
Make other branch for ImmutableJS users

### ISSUE THREAD

**Issue by dalisoft** [pavelivanov/redaction#8]
Hi @pavelivanov.
Good work, thanks for library which makes my things easier & speeds up my development.

But i see npm warnings when installing this library which needs immutablejs, i know warnings not critical, but i want to be everything green and clean.

I hope you understand what i mean.

Thanks again :)

**Comment by pavelivanov** [comment]
Hi @dalisoft.
I appreciate you enjoying the library :) 

Could it be warnings about peer dependencies? There are 3 of them in package.json:

```
"immutable": "^3.0.0",
"react": "^0.14.0 || ^15.0.0-0 || ^16.0.0-0",
"redux": "^2.0.0 || ^3.0.0"
```

**Comment by pavelivanov** [comment]
I had thoughts about removing Immutable from the lib. Mbe it's the time :)

**Comment by dalisoft** [comment]
react-immutable, immutable and redux warnings. One of warning should disappear (redux v4 you merged, thanks).
If someone need immutable variant, they can find easily with separate branch (if we do it as separate branch)

**Comment by pavelivanov** [comment]
I will remove it now. Wait a moment for 5.0.0 :)

**Comment by dalisoft** [comment]
Thank you a lot for quick fix and response

**Comment by pavelivanov** [comment]
@dalisoft done. Check it please. If there will be some problems or any question - fill free to write me email: grammka@gmail.com

**Comment by dalisoft** [comment]
Thanks. Warning are gone. Good work!
Have a nice day :)

**Comment by dalisoft** [comment]
You can see [result of my work](https://github.com/dalisoft/cra-modified-dev-env) which i can't be make without this library (because one of three my focus is using redaction)
